name: Summarize Issues

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  summarize-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Summarize issue
        id: inference
        uses: actions/ai-inference@v1
        with:
          prompt: |
            Please summarize the following issue body in a few sentences.
            Focus on the user's problem and the expected outcome.
            ---
            ${{ github.event.issue.body }}

      - name: Post summary as comment
        env:
          GH_TOKEN: ${{ github.token }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: |
          gh issue comment $ISSUE_NUMBER --body "### AI Summary
          > ${{ steps.inference.outputs.response }}"
